### ISSUE TITLE
Im just dumb.

### ISSUE THREAD

**Issue by Mesogo** [3ijtKwijt/Discord-Rainbow-Role#7]
So I have done everything I could possibly think of. I stayed with the (lame) 60 second interval. Im not getting any error messages or anything. The bot comes online, but it wont do ANYTHING. I checked the audit logs and everything. Is the bot outdated, or am I stupid?
```css
help
```

**Comment by ghost** [comment]
Does the bot have the right permissions?

**Comment by Mesogo** [comment]
> Does the bot have the right permissions?

I sent this issue two years ago

**Comment by RwbyChan** [comment]
You are responsible yourself for the permissions it has when you invite it to your server
